version: '3'
services:
  user1:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: user1
    hostname: user1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=user1
    restart: unless-stopped
    networks:
      - keyscom-network
  user2:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: user2
    hostname: user2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=user2
    restart: unless-stopped
    networks:
      - keyscom-network
  server1:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server1
    hostname: server1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
  server2:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server2
    hostname: server2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
  server3:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server3
    hostname: server3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
  server4:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server4
    hostname: server4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
  server5:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server5
    hostname: server5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
  server6:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server6
    hostname: server6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
  server7:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server7
    hostname: server7
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
  server8:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: server8
    hostname: server8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsPQtQNIIfu8Wr5z59TEoSYCWVw+rloRaGN5x4yWlZSrqtveOnqMEeXitFV6mqLc6lbg4E2JHJnZ9Kw+pDbS5D75YA2F1tF6X6+GrC4BNtpGBAbuQmWxVIac8xrJHniwFdop2fWWjqWoxOPXxr36k7zby3DOg2pgLmDY9pnpaR4d+XMcGKPesGkzErvIo/cm9/qwj7pjI+My8+3k9a4Jq11OEZiFlO2wIb9YHTqltKbmdr5JhV9XaYq/H2H9HIO5OnuUb7REIr7oAGg8EyS9D/l9o6fkSSpcKVWJyAbo2+YNIyw9SQmbrxUyU1if8Kjhn9LN22tVb9/rq7z8DLCOJNfILjQLwQshjC1pO0cpkz5nbSGffKCObBui5ExRKb40OCIvx66JqXEnILrk7Iej9+1Kg1c0Zc4lUeeoK8feExOhn6gX1J6xS28gHLjTZQ82uWLS5oCW01+Ix4sN8xlM/EspH86jjQBFbrXrvLfvxs3dwH7dS1G9+g7MQ0j1r/8Hs= bitsman@MacBook-Air-de-Francisco.local
      - USER_NAME=keyscom
    restart: unless-stopped
    networks:
      - keyscom-network
networks:
  keyscom-network:
    external: true
